<?php

namespace AppBundle\Repository;

/**
 * episodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class episodeRepository extends \Doctrine\ORM\EntityRepository
{
	public function getEpisodesByCountry($country) {
	    return $this->createQueryBuilder('e')
	      ->where('e.country = :country')
	      ->setParameter('country', $country)
	      ->getQuery()
	      ->getResult();
	} // End getEpisodesByCountry()

	public function getEpisodesByCountryByDate($country) {
	    return $this->createQueryBuilder('e')
	      ->where('e.country = :country')
	      ->setParameter('country', $country)
	      ->orderBy('e.dateFrom', 'ASC')
	      ->getQuery()
	      ->getResult();
	} // End getEpisodesByCountryByDate()

	public function findThreeLastId() {
	    return $this->createQueryBuilder('e')
	      ->orderBy('e.id', 'DESC')
	      ->setMaxResults(3)
	      ->getQuery()
	      ->getResult();
	} // End findThreeLastId()
}
