<?php

namespace AppBundle\Repository;

/**
 * subscriberRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class subscriberRepository extends \Doctrine\ORM\EntityRepository
{
}
