# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    uploads_directory: '%kernel.root_dir%/../web/uploads'

services:
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false
        bind:
            $uploadsDirectory: '%uploads_directory%'

    # Twig extensions
    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
            - { name: twig.extension }

    # makes classes in src/AppBundle available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    AppBundle\:
        resource: '../../src/AppBundle/*'
        # you can exclude directories or files
        # but if a service is unused, it's removed anyway
        exclude: '../../src/AppBundle/{Entity,Repository,Tests}'

    # controllers are imported separately to make sure they're public
    # and have a tag that allows actions to type-hint services
    AppBundle\Controller\:
        resource: '../../src/AppBundle/Controller'
        public: true
        tags: ['controller.service_arguments']

    # add more services, or override services that need manual wiring
    # AppBundle\Service\ExampleService:
    #     arguments:
    #         $someArgument: 'some_value'

    #### Controller
    AppBundle\Controller\HomepageController:
        arguments: 
            - '@AppBundle\Service\countryService'
            - '@AppBundle\Service\subscriberService'
            - '@AppBundle\Service\episodeService'

    AppBundle\Controller\CountryController:
        arguments: 
            - '@AppBundle\Service\countryService'
            - '@AppBundle\Service\episodeService'
            - '@AppBundle\Service\fileService'
            - '@AppBundle\Service\cleanStringService'

    AppBundle\Controller\EpisodeController:
        arguments: 
            - '@AppBundle\Service\countryService'
            - '@AppBundle\Service\episodeService'
            - '@AppBundle\Service\fileService'
            - '@AppBundle\Service\cleanStringService'

    #### Repository
    AppBundle\Repository\countryRepository:
        factory: 'Doctrine\ORM\EntityManagerInterface:getRepository'
        arguments:
            - AppBundle\Entity\country

    AppBundle\Repository\episodeRepository:
        factory: 'Doctrine\ORM\EntityManagerInterface:getRepository'
        arguments:
            - AppBundle\Entity\episode

    AppBundle\Repository\subscriberRepository:
        factory: 'Doctrine\ORM\EntityManagerInterface:getRepository'
        arguments:
            - AppBundle\Entity\subscriber

    #### Services
    AppBundle\Service\countryService:
        public: true
        arguments:
            - '@AppBundle\Repository\countryRepository'
            - '@doctrine.orm.entity_manager'
            - '@AppBundle\Service\fileService'

    AppBundle\Service\episodeService:
        public: true
        arguments:
            - '@AppBundle\Repository\episodeRepository'
            - '@doctrine.orm.entity_manager'
            - '@AppBundle\Service\fileService'

    AppBundle\Service\subscriberService:
        public: true
        arguments:
            - '@AppBundle\Repository\subscriberRepository'
            - '@doctrine.orm.entity_manager'

    AppBundle\Service\fileService:
        public: true
        arguments:
            - '%uploads_directory%'
